
[logbegone]
	phrases = ["Disconnecting VANILLA connection attempt", "Channels ", "not creating a ShipObject", "Remove Collision box is too big! AABB"]
	regex = ["Disconnecting VANILLA connection attempt", "Channels ", ".*not creating a ShipObject"]

