#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Nov 04 22:59:26 CET 2024
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=8
shaderPack=[Equilibr\u00E9] ComplementaryUnbound_r5.3 + EuphoriaPatches_1.4.1
enableShaders=true
