#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Jun 07 16:16:55 CEST 2024
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=8
shaderPack=ComplementaryUnbound_r5.2.1 + EuphoriaPatches_1.3.zip
enableShaders=true
