
[Trainers]
	#Determines if symbols for trainer types are shown next to trainer names.
	showTrainerTypeSymbols = false
	#Determines if trainer names are colored based of their type.
	showTrainerTypeColors = true

