#INTERNAL. DO NOT TOUCH
configVersion = 1

#Disable/Enable basic integrations
[common]
	#Should SDLink integrate with Vanish Mod
	vanish = true
	#Should SDLink integrate with FTB Essentials
	ftbessentials = true

#Manage Maintenance Mode integration
[maintenance_mode]
	#Should integration with MaintenanceMode be enabled
	enabled = true
	#Change the Bot Online Status during Maintenance Mode. Valid options are ONLINE, IDLE, DO_NOT_DISTURB, OFFLINE
	maintenanceOnlineStatus = "DO_NOT_DISTURB"
	#Update channel topic with server MOTD during maintenance mode
	updateChannelTopic = true
	#Update the bot status with the server MOTD during maintenance mode
	updateBotStatus = false
	#Send a message to discord when maintenance starts
	sendMaintenanceStart = true
	#Send a message to discord when maintenance ends
	sendMaintenanceEnd = true
	#The message to send to discord when maintenance has started
	maintenanceStartMessage = "Maintenance has started"
	#The message to send to discord when maintenance has ended
	maintenanceEndMessage = "Maintenance has ended"

