#Integer between 0 and 2, determines which widget will be on the main screen (so far from the options only none - 0 - and player's team - 1) | default: 1
mainMenuWidget=1
#Integer, determines the size of the check area (-1 to use the same size as the command) | default: -1
checkSpawnsSizing.width=-1
#Integer, determines the size of the check area (-1 to use the same size as the command) | default: -1
checkSpawnsSizing.height=-1
#Integer, Determines the size of the finding area | default: 100
findingSizing.width=100
#Integer, Determines the size of the finding area | default: 100
findingSizing.height=100
#String array, Determines which pokemon labels will be ignored when spawn checks are run, list separated by commas | default: not_modeled
ignoredPokemonLabels=not_modeled
#Integer between 0 and 4, Determines the permission level for title commands, google for more info | default: 2
titleCommandsPermissionLevel=2
#Integer, Determines the height at which the track arrow will be positioned | default: 70
trackArrowVerticalPosition=70

