
#MineColonies
[minecolonies]
	Enable = true
	#Range: 1 ~ 23999
	AverageNightTime = 12000
	#Range: -6000 ~ 6000
	CheckSleepOffset = 1000

#Ambient Sounds
#The mod is no longer maintained for version 1.20, so we need a mixin to make the sounds work properly during snowfall.
[ambientsounds]
	Enable = true

