
["Shutdowner settings"]

	["Shutdowner settings"."server shutdown hang settings"]
		#Whether to kill the server when shutdown takes too long. default: true
		shouldDetectShutDownHang = true
		#The maximum time the shutdown is allowed to take. default: 120s
		#Range: 1 ~ 20000
		maxShutDownTime = 120
		#Print remaining threads to log? default:true
		printThreads = true

	["Shutdowner settings"."server timed shutdown settings"]
		#Whether to use the timed shutdown default: true
		shouldAutoShutDown = true
		#Set the disconnect message for the players
		disconnectMessage = "Le serveur se redémarre."
		#Shutdown timepoints,, format: ["time1","time2"] e.g. ["18:00","23:00"]
		shutdownTimes = ["4:00", "13:48", "19:00"]
		#Shutting down timed messages, format: [secondsToShutdown;Message] e.g. ["300;Server is restarting in 5min","150;Server is restarting in 2.5min"]
		shutdownMessages = ["300;Le serveur va redémarrer dans 5 min.", "60;1 minute avant le redémarrage.", "0;Redémarrage en cours..."]

	["Shutdowner settings"."server runtime hang settings"]
		#Whether to detect and close the server hang during runtime default: true
		shouldDetectHang = true

