
#Toutes les configurations liées à la base du jeu
[gameplay]
	#Nombre de citoyens initiaux. [Defaut: 4, min: 1, max: 10]
	#Range: 1 ~ 10
	initialcitizenamount = 4
	#Les joueurs peuvent-ils placer une quantité infinie de camps/navires de ravitaillement ? [Defaut: false]
	allowinfinitesupplychests = false
	#Les joueurs peuvent-ils abandonner leur colonie pour en créer une nouvelle facilement ? Remarque : c'est buggé! [Defaut: false]
	allowinfinitecolonies = false
	#Est-ce que les colonies dans les autres dimensions sont autorisées ? [Defaut: true]
	allowotherdimcolonies = true
	#Nombre max de citoyens dans une colonie. [Defaut: 250, min: 25, max: 500]
	#Range: 25 ~ 500
	maxcitizenpercolony = 250
	#Les fonctionnalités en développement doivent-elles êtres activées (peut être buggé)? [Defaut: false]
	enableindevelopmentfeatures = false
	#Les noms des citoyens doivent-ils être affichés ? [Defaut: true]
	alwaysrendernametag = false
	#Les travailleurs doivent-ils travailler sous la pluie? [Defaut: false]
	workersalwaysworkinrain = true
	#Chance que le Mineur obtienne un minerai en minant de la pierre (par défaut, il peut être étendu avec des datapacks à d'autres matériaux). C'est un pourcentage. (Pour changer quels minerais le Mineur peut trouver, regardez "Liste des Minerais Chanceux".) [Defaut: 1, min: 0, max: 100]
	#Range: 0 ~ 100
	luckyblockchance = 1
	#Le niveau minimum qu'un hôtel de ville doit avoir pour permettre la téléportation vers les colonies alliées. [Defaut: 3, min: 0, max: 5]
	#Range: 0 ~ 5
	minthleveltoteleport = 3
	#Modificateur de la consommation alimentaire. [Defaut: 1.000000, min: 0.100000, max: 100.000000]
	#Range: 0.1 ~ 100.0
	foodmodifier = 1.0
	#A quel point les maladies sont courantes. 1 = Très commun, 100 = Extrêmement rare. [Defaut: 5, min: 1, max: 100]
	#Range: 1 ~ 100
	diseasemodifier = 10
	#Si une partie de la colonie est chargée par un propriétaire/agent, la colonie doit-elle rester chargée ? (Définissez le nombre de morceaux à charger avec l'option "Colony Chunk Loading Strictness") [Defaut: true]
	forceloadcolony = true
	#Définit la durée pendant laquelle les blocs restent chargés après le départ du joueur, ne persiste pas lors des redémarrages. Valeur par défaut : 10min [Defaut: 10, min: 1, max: 1440]
	#Range: 1 ~ 1440
	loadtime = 10
	#Cela contrôle combien de chunks sont chargés avec l'option "Chunk Load Colony". Plus la valeur est élevée, moins de chunks seront chargés. (Les chunks centraux seront chargés en premier.) 1 = charge de tous les chunks visités. [Defaut: 3, min: 1, max: 15]
	#Range: 1 ~ 15
	colonyloadstrictness = 3
	#Le nombre maximum de bûches d'un arbre pour le Forestier à vérifier pendant la recherche de son arbre. [Defaut: 400, min: 1, max: 1000]
	#Range: 1 ~ 1000
	maxtreesize = 400
	#Désactive les restrictions de placement des camps d'approvisionnement, pour les skyworld et similaire [Defaut: false]
	nosupplyplacementrestrictions = false
	#Les attaquants apparaitront dans le ciel si activé [Defaut: false]
	skyraiders = false

#Toutes les configurations liées au système de requête
[research]
	#Permet l'achèvement automatique et (presque) instantané des recherches pour les joueurs en mode créatif. Si elle est fausse, les joueurs en mode créatif pourront toujours commencer des recherches, mais auront des taux de progression normaux. [Defaut: true]
	researchcreativecompletion = true
	#Augmente significativement la quantité d'information relative aux datapacks de recherches loggée pendant le chargement d'un monde. [Defaut: false]
	researchdebuglog = false
	#Une liste d'éléments à facturer aux joueurs lorsqu'ils annulent une recherche déjà effectuée. 
	researchresetcost = ["minecolonies:ancienttome:1"]

#Toutes les configurations liées aux commandes Minecolonies
[commands]
	#Les joueurs devraient-ils être autorisés à utiliser la commande /mc rtp? [Defaut: false]
	canplayerusertpcommand = false
	#Est-ce que les joueurs devraient être autorisés à utiliser la commande "/mc colony teleport" ? [Defaut: false]
	canplayerusecolonytpcommand = false
	#Les joueurs peuvent-ils se téléporter vers les colonies alliées ? [Defaut: true]
	canplayeruseallytownhallteleport = true
	#Les joueurs devraient-ils être autorisés à utiliser la commande "/mc maison"? Remarque: Seul le propriétaire de la colonie peut utiliser cette commande. [Defaut: false]
	canplayerusehometpcommand = false
	#Les joueurs devraient-ils être autorisés à utiliser la commande /mc colony info ? [Defaut: true]
	canplayeruseshowcolonyinfocommand = true
	#Les joueurs devraient-ils être autorisés à utiliser la commande /mc citizens kill ? [Defaut: false]
	canplayerusekillcitizenscommand = false
	#Les joueurs doivent-ils être autorisés à utiliser la commande /mc colony addOfficer ? [Defaut: true]
	canplayeruseaddofficercommand = true
	#Les joueurs devraient-ils être autorisés à utiliser la commande /mc colony delete ? [Defaut: false]
	canplayerusedeletecolonycommand = false
	#Les joueurs doivent-ils être autorisés à utiliser la commande /mc colony requestsystem-reset ? [Defaut: false]
	canplayeruseresetcommand = false
	#Les joueurs devraient-ils être autorisés à utiliser la commande /mc citizens modify ? [Defaut: false]
	canplayerusemodifycitizenscommand = false

#Toutes les configurations liées à la taille d’une colonie
[claims]
	#Distance de réclamation maximale pour une colonie. C'est le rayon, mesuré en chunks. [Defaut: 20, min: 1, max: 250]
	#Range: 1 ~ 250
	maxColonySize = 20
	#La distance minimale (en chunks) entre les colonies. [Defaut: 8, min: 1, max: 200]
	#Range: 1 ~ 200
	minColonyDistance = 20
	#Taille initiale de la revendication pour une colonie. C'est le rayon, mesuré en chunks. [Defaut: 4, min: 1, max: 15]
	#Range: 1 ~ 15
	initialColonySize = 4
	#Distance maximale (en blocs) des apparitions des colonies dans le monde. [Defaut: 30000, min: 1000, max: 2147483647]
	#Range: > 1000
	maxdistancefromworldspawn = 30000
	#Distance minimale (en blocs) des apparitions des colonies dans le monde. [Defaut: 0, min: 0, max: 1000]
	#Range: 0 ~ 1000
	mindistancefromworldspawn = 0

#Toutes les configurations liées aux éléments de combat de MineColonies
[combat]
	#minecolonies.config.dobarbariansspawn.comment [Defaut: true]
	dobarbariansspawn = false
	#minecolonies.config.barbarianhordedifficulty.comment [Defaut: 5, min: 0, max: 10]
	#Range: 0 ~ 10
	barbarianhordedifficulty = 5
	#minecolonies.config.maxbarbariansize.comment [Defaut: 80, min: 6, max: 400]
	#Range: 6 ~ 400
	maxBarbarianSize = 80
	#minecolonies.config.dobarbariansbreakthroughwalls.comment [Defaut: true]
	dobarbariansbreakthroughwalls = false
	#Le nombre moyen de nuits entre les raids. [Defaut: 14, min: 1, max: 50]
	#Range: 1 ~ 50
	averagenumberofnightsbetweenraids = 30
	#Le nombre minimum de nuits entre les raids. [Defaut: 10, min: 1, max: 30]
	#Range: 1 ~ 30
	minimumnumberofnightsbetweenraids = 20
	#Les monstres devraient-ils attaquer les citoyens? [Defaut: true]
	mobattackcitizens = true
	#minecolonies.config.shouldraiderbreakdoors.comment [Defaut: true]
	shouldraiderbreakdoors = true
	#minecolonies.config.guarddamagemultiplier.comment [Defaut: 1.000000, min: 0.100000, max: 15.000000]
	#Range: 0.1 ~ 15.0
	guardDamageMultiplier = 1.0
	#Multiplicateur de santé pour tous les gardes. [Defaut: 1.000000, min: 0.100000, max: 5.000000]
	#Range: 0.1 ~ 5.0
	guardhealthmult = 1.0
	#Activez le mode PVP de MineColonies (les colonies peuvent être détruites et anéanties dans certaines conditions). [Defaut: false]
	pvp_mode = false

#Toutes les options de configuration de permissions
[permissions]
	#La protection des colonies doit-elle être activée ? [Defaut: true]
	enablecolonyprotection = false
	#Indépendamment de la protection de la colonie, les explosions doivent-elles être enlevées à l'intérieur des colonies ? DAMAGE_NOTHING prévient de toutes les explosions. DAMAGES_PLAYERS, autorise les explosions à faire des dégâts aux joueurs et aux créatures agressives, mais pas aux blocs, ni aux créatures neutres et amicales. DAMAGES_ENTITIES autorise les dégâts à toutes les entités. DAMAGE_EVERYTHING autorise les explosions aux entités et aux blocs. 
	#Allowed Values: DAMAGE_NOTHING, DAMAGE_PLAYERS, DAMAGE_ENTITIES, DAMAGE_EVERYTHING
	turnoffexplosionsincolonies = "DAMAGE_ENTITIES"
	#Désactive les autorisations de colonie si le joueur possède un niveau d'autorisation donné. [Defaut: 2, min: 0, max: 4]
	#Range: 0 ~ 4
	permissioneventbypassminpermlevel = 2

#Toutes les configurations liées à la compatibilité entre mods
[compatibility]
	#Au chargement des recettes, un fichier d'audit CSV se génère pour vous aider à déboguer les datapacks ou autres mods. [Defaut: false]
	auditcraftingtags = false
	#Active le débogage de l'inventaire. [Defaut: false]
	debuginventories = false
	#Cochez si vous utilisez ce monde pour la construction ou scanner via un Blueprint. [Defaut: false]
	blueprintbuildmode = false

#Toutes les configurations liées au pathfinding
[pathfinding]
	#Détail des messages de débogage du Pathfinding. [Defaut: 0, min: 0, max: 10]
	#Range: 0 ~ 10
	pathfindingdebugverbosity = 0
	#Nombre minimum de rails consécutifs pour que les citoyens puissent les utiliser. [Defaut: 8, min: 5, max: 100]
	#Range: 5 ~ 100
	minimumrailstopath = 8
	#Nombre de processus additionnels à utiliser pour le Pathfinding. [Defaut: 1, min: 1, max: 10]
	#Range: 1 ~ 10
	pathfindingmaxthreadcount = 2

#Toutes les configurations liées au système de requête
[requestSystem]
	#Est-ce que le système de requête doit résoudre créativement (si possible) quand le joueur est demandé à résoudre une requête ? C'est un outil de débogage et cela peut prendre très longtemps avant de résoudre la requête. [Defaut: false]
	creativeresolve = false

